name: Docker Build & Test

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t pshrestha/frontend -f Dockerfile.dev .
